### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by do3les** [do3les/InfLocher-Tower-Defense#34]
Rewrite and restructure the code.

**Comment by moisesAlc** [comment]
Hi @do3les , everything all right? I know someone who can help you refactor: [`Magoninho`](https://github.com/Magoninho)

**Comment by do3les** [comment]
Hi @moisesAlc , yes, we're fine. Thanks very much for the offer, but this is a school project, so we aren't looking for contributors. 
(I guess I should write that in the README)
